
package auction.webservice.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FacadeService", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FacadeService {


    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "firstLoadSystem", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.FirstLoadSystem")
    @ResponseWrapper(localName = "firstLoadSystemResponse", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.FirstLoadSystemResponse")
    @Action(input = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/firstLoadSystemRequest", output = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/firstLoadSystemResponse")
    public boolean firstLoadSystem();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "releaseResource", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.ReleaseResource")
    @ResponseWrapper(localName = "releaseResourceResponse", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.ReleaseResourceResponse")
    @Action(input = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/releaseResourceRequest", output = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/releaseResourceResponse")
    public void releaseResource();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userRegistration", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.UserRegistration")
    @ResponseWrapper(localName = "userRegistrationResponse", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.UserRegistrationResponse")
    @Action(input = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/userRegistrationRequest", output = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/userRegistrationResponse")
    public boolean userRegistration(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @return
     *     returns java.util.List<auction.webservice.client.Lot>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadAllLots", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.LoadAllLots")
    @ResponseWrapper(localName = "loadAllLotsResponse", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.LoadAllLotsResponse")
    @Action(input = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/loadAllLotsRequest", output = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/loadAllLotsResponse")
    public List<Lot> loadAllLots();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addLot", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.AddLot")
    @ResponseWrapper(localName = "addLotResponse", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.AddLotResponse")
    @Action(input = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/addLotRequest", output = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/addLotResponse")
    public boolean addLot(
        @WebParam(name = "arg0", targetNamespace = "")
        Lot arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelLot", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.CancelLot")
    @ResponseWrapper(localName = "cancelLotResponse", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.CancelLotResponse")
    @Action(input = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/cancelLotRequest", output = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/cancelLotResponse")
    public boolean cancelLot(
        @WebParam(name = "arg0", targetNamespace = "")
        Lot arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBid", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.AddBid")
    @ResponseWrapper(localName = "addBidResponse", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.AddBidResponse")
    @Action(input = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/addBidRequest", output = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/addBidResponse")
    public boolean addBid(
        @WebParam(name = "arg0", targetNamespace = "")
        Lot arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Bid arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns auction.webservice.client.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userAuthentication", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.UserAuthentication")
    @ResponseWrapper(localName = "userAuthenticationResponse", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", className = "auction.webservice.client.UserAuthenticationResponse")
    @Action(input = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/userAuthenticationRequest", output = "http://auction.facadeservice/jaxws/auctionservice/FacadeService/userAuthenticationResponse")
    public User userAuthentication(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
