
package client.artefacts;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuctionService", targetNamespace = "http://auction.facadeservice/jaxws/auctionservice", wsdlLocation = "http://localhost:8080/Auction/AuctionService?wsdl")
public class AuctionService
    extends Service
{

    private final static URL AUCTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUCTIONSERVICE_EXCEPTION;
    private final static QName AUCTIONSERVICE_QNAME = new QName("http://auction.facadeservice/jaxws/auctionservice", "AuctionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Auction/AuctionService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUCTIONSERVICE_WSDL_LOCATION = url;
        AUCTIONSERVICE_EXCEPTION = e;
    }

    public AuctionService() {
        super(__getWsdlLocation(), AUCTIONSERVICE_QNAME);
    }

    public AuctionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUCTIONSERVICE_QNAME, features);
    }

    public AuctionService(URL wsdlLocation) {
        super(wsdlLocation, AUCTIONSERVICE_QNAME);
    }

    public AuctionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUCTIONSERVICE_QNAME, features);
    }

    public AuctionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuctionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FacadeService
     */
    @WebEndpoint(name = "AuctionServicePort")
    public FacadeService getAuctionServicePort() {
        return super.getPort(new QName("http://auction.facadeservice/jaxws/auctionservice", "AuctionServicePort"), FacadeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FacadeService
     */
    @WebEndpoint(name = "AuctionServicePort")
    public FacadeService getAuctionServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://auction.facadeservice/jaxws/auctionservice", "AuctionServicePort"), FacadeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUCTIONSERVICE_EXCEPTION!= null) {
            throw AUCTIONSERVICE_EXCEPTION;
        }
        return AUCTIONSERVICE_WSDL_LOCATION;
    }

}
